### ISSUE TITLE
After AUTHORIZE I get: URI must be a string or UriInterface

### ISSUE THREAD

**Issue by cristian-dan-f** [tkhamez/eve-sso-php#2]
After AUTHORIZE and redirected back to auth callback url (`redirectUri`) I get a blank page saying:

`URI must be a string or UriInterface`

The URI it refers to must be `urlAccessToken` since is the step it should be runing.

Everything is correctly setup, I can't find any missing information, although your instruction in the README for the
`// Callback URL`

directly uses provider without showing how to intialize it:
`$auth = $provider->validateAuthenticationV2($_GET['state'], $_SESSION['state'], $_GET['code']); // SSO v2`

and whats worse, if I try to init $provider with the instructions available, it throws a fatal error. See issue #1

**Comment by tkhamez** [comment]
The provider object is initiated the same for both places. I suppose I can make that more clear in the example.

Where do you get this error? Can you please try again with the latest version and provide the complete error message with a stack trace.

**Comment by cristian-dan-f** [comment]
`URI must be a string or UriInterface` is all the error I get. Is right after redirect back to my domain to the Callback URL, after Login with EVE Online account.

I already suposed it was initiated same way in both cases, but something goes wrong with the URI that gets the access/refresh token.

**Comment by tkhamez** [comment]
Can't reproduce.
